FROM quay.io/keycloak/keycloak:20.0.1

ARG THEME
ENV KEYCLOAK_HOME=/opt/keycloak
ENV KC_DB=mysql
ENV KC_HTTP_RELATIVE_PATH=/auth

WORKDIR ${KEYCLOAK_HOME}

COPY ./themes/${THEME}-theme themes/${THEME}-theme

RUN ${KEYCLOAK_HOME}/bin/kc.sh build

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false"]